benzhu_coupon/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
from benzhu_coupon.apps.statistics.views import *
from benzhu_coupon.apps.atom.views import *
from benzhu_coupon.apps.coupon.views import *
from benzhu_coupon.apps.bzmember.views import *
from benzhu_coupon.apps.company.views import *
from benzhu_coupon.apps.wechat.cardpack.views import *
from benzhu_coupon.apps.game.guest_it.views import guest 
from benzhu_coupon.apps.game.shake_it.views import shake 
from benzhu_coupon.apps.game.get_it.views import get 
from benzhu_coupon.apps.game.luck_draw.views import luck_draw, get_ld_members, is_drawed, result_confirm 

# urlpatterns.
urlpatterns = patterns('',
    url(r'^$', all_coupons),
    url(r'^search_by_taxonomy/$', search_coupons_by_taxonomy),
    url(r'^search_by_way/$', search_coupons_by_way),

    url(r'^stop/$', stop),

    url(r'^coupon/(\d+)/$', coupon_detail),
    url(r'^coupon/(\d+)/company$', coupon_company),
    url(r'^coupon/(\d+)/get/$', coupon_get),

    url(r'^coupon/(\d+)/fetch/$', coupon_fetch),
    url(r'^coupon/(\d+)/go/$', coupon_go),

    url(r'^info_list/$', info_list),
    url(r'^info_list/(\d+)/$', info_detail),
    
    url(r'^center', center),
    url(r'^my_coupon/(\d+)/$', my_coupon_detail),
    url(r'^my_coupon/type/(\d+)&(\d+)/$', search_my_coupons_two_types),
    url(r'^my_coupon/type/(\d+)/$', search_my_coupons),
    url(r'^my_lotteries/(\d+)/$', all_my_lotteries),
    url(r'^coupon/(\d+)/win_list/', coupon_win_list),
    url(r'^about/$', about),
    url(r'^about_us/', about_us),
    url(r'^safeguard/', safeguard),

    url(r'^company_login', company_login),
    url(r'^company_center/$', company_center),
    url(r'^company_center/(\d+)/$', company_coupon_detail),
    url(r'^company_center/(\d+)/win_list/$', company_coupon_win_list),
    url(r'^company_center/(\d+)/way_list/$', company_coupon_way_list),
    url(r'^company_center/(\d+)/check/$', coupon_check),
    url(r'^company_center/setting/$', company_setting),
    url(r'^company_center/consume/$', consume),
    url(r'^company_center/setting/change_password/$', company_password),
    url(r'^company_center/setting/company_info', company_info),
    url(r'^company_logout', company_logout),

    url(r'^list', list),
    url(r'^bzadmin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^login', login),
    url(r'^fl', fastlogin),
    url(r'^logout', logout),

    url(r'^game/guest', guest),
    url(r'^game/shake', shake),
    url(r'^game/get', get),
    url(r'^game/luck_draw$', luck_draw),
    
    url(r'^game/luck_draw/get_ld_members/(\d+)/$', get_ld_members ),
    url(r'^game/luck_draw/is_drawed/(\d+)/$', is_drawed ),
    url(r'^game/luck_draw/result_confirm/(\d+)/$', result_confirm),

    url(r'^tongji', tongji),
    url(r'^cardpack/test/$', cardpack),
    url(r'^cardpack/get_simple_card_list/$', SimpleCardList.as_view()),
    url(r'^cardpack/get_card/$', GetCard.as_view()),
    url(r'^cardpack/set_log/$', wx_write_log),
    url(r'^cardpack/get_all_cards/$', get_all_cards),
)

# Append
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

benzhu_coupon/apps/wechat/cardpack/models.py
from django.db import models
from benzhu_coupon.apps.company.models import Company
from benzhu_coupon.apps.bzmember.models import BzMember
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from django.core.cache import cache
from django.utils import timezone

import urllib2, json, uuid


class WechatCompany(models.Model):
    company = models.ForeignKey(Company, null=False, blank=False)

    app_id = models.CharField(_('Application ID'), max_length=30, default='', null=False, blank=False, unique=True)
    app_secret = models.CharField(_('Application Secret'), max_length=50, default='', null=False, blank=False)

    class Meta:
        verbose_name = _('Wechat Company')
        verbose_name_plural = _('Wechat Companies')

    def __unicode__(self):
        return self.company.name

    def get_access_token(self):
        # get access token.
        # limited. catched.
        
        access_token_ideography = 'access_token_'+(self.app_id)
        
        if cache.get(access_token_ideography):
            return cache.get(access_token_ideography)
        else:
            url = 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s'
            credential = urllib2.urlopen( url % (self.app_id, self.app_secret) )
            credential = eval( credential.read() )
            print credential
            try:
                access_token = credential['access_token']
                cache.set(access_token_ideography, access_token, credential['expires_in'])
            except KeyError:
                return None

            return access_token

    def reset_access_token(self):
        # get wrong token, reset it.

        access_token_ideography = 'access_token_'+(self.app_id) 
        if cache.has_key(access_token_ideography):
            cache.delete(access_token_ideography)
            print 'reset_access_token'
            return get_access_token()

    def get_api_ticket(self, ticket_type='wx_card'):
        # get api_ticket.
        # limited. catched.
        
        api_ticket_ideography = 'api_ticket_'+ticket_type+'_'+(self.app_id)
        
        if cache.get(api_ticket_ideography):
            return cache.get(api_ticket_ideography)
        else:
            url = 'https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=%s' #jsapi, wx_card
            credential = urllib2.urlopen( url % (self.get_access_token(), ticket_type) )
            credential = eval( credential.read() )
            print credential
            try:
                api_ticket = credential['ticket']
                cache.set(api_ticket_ideography, api_ticket, credential['expires_in'])
            except KeyError:
                return None

            return api_ticket

    def batch_get_cards(self):
        # batch get cards.
        batchget_post = { "offset": "0", "count": "50", "status_list": ["CARD_STATUS_VERIFY_OK", "CARD_STATUS_DISPATCH"] }
        url = 'https://api.weixin.qq.com/card/batchget?access_token=%s'
        
        batch_get_cards_id = lambda act: urllib2.urlopen( data = json.dumps(batchget_post), url = url % act )

        f = batch_get_cards_id(self.get_access_token())
        cards = eval( f.read() )

        try:
            print cards['card_id_list']
        except KeyError:
            if cards['errcode'] == 40001:
                f = batch_get_cards_id(self.reset_access_token())
                cards = eval( f.read() )

        simple_cards = []
        for card_id in cards['card_id_list']:
            # read card details.
            card = urllib2.urlopen(
                data = json.dumps({ "card_id": card_id }),
                url = 'https://api.weixin.qq.com/card/get?access_token=%s' % self.get_access_token() )

            # replace boolean variable for eval operation.
            true, false = True, False 
            card_info = eval(card.read())

            simple_cards.append({   
                'company': self.id, 
                'original_company': self.company.pk,
                'card_id': card_id, 
                'color': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['color'],
                'logo_url': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['logo_url'],
                'title': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['title'], 
                'description': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['notice'], 
            })

        return json.dumps(simple_cards)


class WechatCard(models.Model):
    wechat_company = models.ForeignKey(WechatCompany, null=False, blank=False)
    title = models.CharField(_('Title'), max_length=255, default='', null=False, blank=False)
    custom_company = models.ForeignKey(Company, null=False, blank=False)
    description = models.CharField(_('Description'), max_length=2000, default='', null=True, blank=True)
    card_id = models.CharField(_('Card ID'), max_length=32, default='', null=False, blank=False)
    logo_img = models.CharField(_('Logo Images Url'), max_length=255, default='', null=False, blank=False)
    color = models.CharField(_('Color'), max_length=10, default='', null=False, blank=False)
    url_uuid = models.CharField(_('URL UUID'), max_length=100, default=hex(int(uuid.uuid1())), null=False, blank=False, unique=True)

    class Meta:
        verbose_name = _('Wechat Card')
        verbose_name_plural = _('Wechat Cards')

    def __unicode__(self):
        return self.title


class WechatLog(models.Model):
    user = models.ForeignKey(BzMember, null=True, blank=True) 
    wechatcard = models.ForeignKey(WechatCard, null=True, blank=True) 
    action = models.CharField(_('Action'), max_length=255, default='', null=True, blank=True)
    memo = models.CharField(_('Memo'), max_length=2000, default='', null=True, blank=True)
    action_time = models.DateTimeField(_('Action Time'), default=timezone.now)

    class Meta:
        verbose_name = _('Wechat Log')
        verbose_name_plural = _('Wechat Logs')

benzhu_coupon/apps/wechat/cardpack/views.py
#coding=utf-8

from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.template import loader, Context
from django.conf import settings 
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.core.cache import cache
from django.views.generic import View
from django.views.decorators.cache import cache_page

from .models import WechatCompany, WechatCard, WechatLog

import json
import random, time
import hashlib
import urllib2


def get_all_cards(request):
    cards = WechatCard.objects.all()
    return render_to_response('cardpack_staff.html', 
            { 'cards': cards }, context_instance=RequestContext(request))


def wx_write_log(request):
    action = request.GET.get('action')
    if action == 'add_card:ok':
        uuid = request.GET.get('uuid')
        log = WechatLog()
        log.user = request.user
        log.action = action
        log.wechatcard = get_object_or_404(WechatCard, url_uuid=uuid)
        log.save()
    pass


def get_jsapi_sign(request):
    # generate jsapi signature
    # static
    noncestr = 'Wm3WZYTPz0wzccnW'
    url = 'http://%s%s' % (request.get_host(), request.get_full_path())
    sign_str = 'jsapi_ticket=%s&noncestr=%s&timestamp=%d&url=%s'
    timestamp = int(time.time()) 

    # dynamic
    try:
        company = WechatCompany.objects.get(app_id='wxa6932e688742e714')
    except WechatCompany.DoesNotExist:
        # some error occur here. FIX IT.
        company = card.wechat_company

    sign_str = sign_str % ( company.get_api_ticket('jsapi'), noncestr, timestamp, url )
    jsapi_signature = hashlib.sha1(sign_str).hexdigest()

    print '*******************'
    print sign_str
    print jsapi_signature
    print '*******************'

    # get jsapi config info & signature.
    jsapi_config = { 'appid' : company.app_id, 'timestamp': timestamp, 'noncestr' : noncestr, 'signature': jsapi_signature, }

    return jsapi_config


class SimpleCardList(View):
    def get(self, request):
        company_id = int(request.GET.get('company')) 
        json_cards = get_object_or_404(WechatCompany, pk=company_id).batch_get_cards()
        return HttpResponse(json_cards)


class GetCard(View):
    def get(self, request):
        url_uuid = request.GET.get('card_id')
        card = get_object_or_404(WechatCard, url_uuid=url_uuid)
        print card

        # generate card signature.
        timestamp = int(time.time())

        #card.wechat_company.app_secret
        sign = [ card.card_id, card.wechat_company.get_api_ticket(), timestamp ]
        sign.sort()
        sign_str = ''.join(map(str,sign))
        card_signature = hashlib.sha1(sign_str).hexdigest()

        print sign

        # read card details.
        card_detail = urllib2.urlopen(
            data = json.dumps({ "card_id": card.card_id }),
            url = 'https://api.weixin.qq.com/card/get?access_token=%s' % card.wechat_company.get_access_token() )
        true, false = True, False
        card_info = eval(card_detail.read())

        print card_info        

        # generate jsapi signature
        jsapi_config = get_jsapi_sign(request)
        print jsapi_config

        card = { 
                'card_id': card.card_id, 
                'card_name': card.title, 
                'company': card.wechat_company.company.name, 
                'color': card.color, 
                'logo_url': card.logo_img, 
                'notice': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['notice'], 
                'received': card_info['card'][card_info['card']['card_type'].lower()]['base_info']['sku']['total_quantity'] - 
                            card_info['card'][card_info['card']['card_type'].lower()]['base_info']['sku']['quantity'], 
                'timestamp': timestamp, 
                'signature': card_signature, 
        }
        return render_to_response('shake_cardpack.html', 
                { 'jsapi_config': jsapi_config, 'card': card }, context_instance=RequestContext(request))


def cardpack(request):

    #appid = 'wxa6932e688742e714'
    #secret = '6fd4aa277fd062f41737a2333fc81736'
    appid = 'wx4270e953fa77a5f7'
    secret = '5fc4c32284a81375fc7284421f9bf42e'

    timestamp = int(time.time())

    # get access token.
    # limited. MUST BE rewrite.
    credential = urllib2.urlopen('https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s' % (appid, secret) )
    access_token = eval( credential.read() )['access_token']

    # get api_ticket.
    # limited. MUST BE rewrite.
    api_ticket = urllib2.urlopen('https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi' % access_token)
    api_ticket = eval(api_ticket.read())['ticket']

    print api_ticket

    # generate jsapi signature
    noncestr = 'Wm3WZYTPz0wzccnW'
    url = 'http://bz088.com:8001/cardpack/test/'
    sign_str = 'jsapi_ticket=%s&noncestr=%s&timestamp=%d&url=%s' % ( api_ticket, noncestr, timestamp, url )
    jsapi_signature = hashlib.sha1(sign_str).hexdigest()
    print sign_str
    print jsapi_signature

    # batch get cards.
    batchget_post = { "offset": "0", "count": "5" }
    f = urllib2.urlopen( data = json.dumps(batchget_post), url='https://api.weixin.qq.com/card/batchget?access_token=%s' % access_token )
    cards = eval( f.read() )

    random_card_index = int( random.random() * len(cards['card_id_list']))
    card_id = cards['card_id_list'][random_card_index]

    print card_id

    # read card details.
    card = urllib2.urlopen(
        data = json.dumps({ "card_id": card_id }),
        url = 'https://api.weixin.qq.com/card/get?access_token=%s' % access_token )

    card_info = card.read()

    # generate card signature.
    sign = [ card_id, secret, timestamp ]
    sign.sort()
    sign_str = ''.join(map(str,sign))
    card_signature = hashlib.sha1(sign_str).hexdigest()

    print card_signature

    # get jsapi config info & signature.
    jsapi_config = { 'appid' : appid, 'timestamp': timestamp, 'noncestr' : noncestr, 'signature': jsapi_signature, }

    # replace boolean variable for eval operation.
    true, false = True, False 
    card = { 'card_id': card_id, 'card_info': eval( card_info ), 'signature': card_signature, }

    print card['card_info']['card']['general_coupon']['base_info']['title']
    print jsapi_config

    return render_to_response('shake_cardpack.html', 
            { 'jsapi_config': jsapi_config, 'card': card }, context_instance=RequestContext(request))

benzhu_coupon/apps/wechat/cardpack/templates/cardpack.html
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<meta content="black" name="apple-mobile-web-app-status-bar-style">
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
wx.config({
    debug: true,
	appId: '{{jsapi_config.appid}}',
	timestamp: {{jsapi_config.timestamp}}, 
	nonceStr: '{{jsapi_config.noncestr}}', 
	signature: '{{jsapi_config.signature}}',
    jsApiList: ['bathAddCard',]
});
</script>
</head>

<body style="background-color: black;">
	<br/>
	<a href="#" id="batchAddCard" style="color: lime; text-decoration:;">Click me for getting more coupons!</a>

<script>
var readyFunc = function onBridgeReady() { 
	document.querySelector('#batchAddCard').addEventListener('click', function(e) {
		WeixinJSBridge.invoke('batchAddCard', 
		{ "card_list": [
			{
				"card_id": "{{card.card_id}}", 
				"card_ext": "{\"code\":\"\",\"openid\":\"\",\"timestamp\":\"{{jsapi_config.timestamp}}\",\"signature\":\"{{card.signature}}\"}"
			}, ]
		}, function(res) {}); 
	}); 
}

if (typeof WeixinJSBridge === "undefined") { 
	document.addEventListener('WeixinJSBridgeReady', readyFunc, false); 
} 
else { 
	readyFunc(); 
}
</script>
</body>
</html>

benzhu_coupon/apps/wechat/cardpack/templates/change_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify static %}

{% block extrahead %}{{ block.super }}
<script type="text/javascript" src="{% url 'admin:jsi18n' %}"></script>
<script type="text/javascript" src="{% static '/static/js/jquery.min.js' %}"></script>
<script type="text/javascript">
// Wechat card getter.
$( function() {
	$('#id_wechat_company').bind('change', 
		function() {
			// Ajax loading.
			loading_text = "{% trans 'Loading' %}...";

			$('#select_card option:first').html(loading_text);
			$('#id_title').val(loading_text);

			// Get ajax company list.
			$.ajax({ 
				url: "/cardpack/get_simple_card_list/?company=" + 
					parseInt( $(this).val() ), 
				dataType: "json", 
				success: function(data) {
					$('#select_card').remove();
					$('#id_title').parent().append('<select id="select_card">');
					$('#id_title').hide();

					for(i in data)
						$('#select_card').append( '<option value="'+ i +'">'+ data[i].title + '</option>' );

					//$('#id_card_id').val( data[$('#select_card').val()].card_id );
					//$('#id_title').val( $('#select_card').find( '[value="'+$('#select_card').val()+'"]' ).text() );	

					$('#select_card').bind('change', 
						function() { 
							$('#id_card_id').val( data[$(this).val()].card_id ).attr("readonly","readonly"); 
							$('#id_logo_img').val( data[$(this).val()].logo_url ); 
							$('#id_custom_company').val( data[$(this).val()].original_company ); 
							$('#id_description').val( data[$(this).val()].description ); 
							$('#id_color').val( data[$(this).val()].color ).attr("readonly","readonly"); 
							$('#id_title').val( $('#select_card').find( '[value="'+$('#select_card').val()+'"]' ).text() );	
					});
					$('#select_card').change();
				},
				error: function (data, status, e){ 
					$('#select_card option:first').html(e);	
					$('#select_card option:first').attr('selected','true');
				},
			});	   
		}
	);
});
</script>
{{ media }}
{% endblock %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />{% endblock %}

{% block coltype %}colM{% endblock %}

{% block bodyclass %}{{ block.super }} app-{{ opts.app_label }} model-{{ opts.model_name }} change-form{% endblock %}

{% if not is_popup %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; {% if has_change_permission %}<a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural|capfirst }}</a>{% else %}{{ opts.verbose_name_plural|capfirst }}{% endif %}
&rsaquo; {% if add %}{% trans 'Add' %} {{ opts.verbose_name }}{% else %}{{ original|truncatewords:"18" }}{% endif %}
</div>
{% endblock %}
{% endif %}

{% block content %}<div id="content-main">
{% block object-tools %}
{% if change %}{% if not is_popup %}
  <ul class="object-tools">
    {% block object-tools-items %}
    <li>
        {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
        <a href="{% add_preserved_filters history_url %}" class="historylink">{% trans "History" %}</a>
    </li>
    {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif%}
    {% endblock %}
  </ul>
{% endif %}{% endif %}
{% endblock %}
<form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
<div>
{% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
{% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}
{% if save_on_top %}{% block submit_buttons_top %}{% submit_row %}{% endblock %}{% endif %}
{% if errors %}
    <p class="errornote">
    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
    {{ adminform.form.non_field_errors }}
{% endif %}

{% block field_sets %}
{% for fieldset in adminform %}
  {% include "admin/includes/fieldset.html" %}
{% endfor %}
{% endblock %}

{% block after_field_sets %}{% endblock %}

{% block inline_field_sets %}
{% for inline_admin_formset in inline_admin_formsets %}
    {% include inline_admin_formset.opts.template %}
{% endfor %}
{% endblock %}

{% block after_related_objects %}{% endblock %}

{% block submit_buttons_bottom %}{% submit_row %}{% endblock %}

{% if adminform and add %}
    <script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                $('form#{{ opts.model_name }}_form :input:visible:enabled:first').focus()
            });
        })(django.jQuery);
    </script>
{% endif %}

{# JavaScript for prepopulated fields #}
{% prepopulated_fields_js %}

</div>
</form></div>
{% endblock %}